name: dotnet package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
        if: github.event_name == 'push' || github.event_name == 'release'
        with:
          fetch-depth: 0
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_EU_DEV_JSON_KEY }}
      - name: Setup tags for docker image
        run: |
            docker_tag_with_branch(){
               GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')
               GIT_COMMIT=$(git log -1 --format=%h )
               DOCKER_TAG=${GIT_BRANCH}-${GIT_COMMIT}
            }

            GH_EVENT_NAME="${{ github.event_name }}"
            GH_ACTION_NAME="${{ github.event.action}}"
            DOCKER_REPO_DATA_AGGREGATOR="eu.gcr.io/dev-container-repo/ng-data-aggregator"
            DOCKER_REPO_GATEWAY_API="eu.gcr.io/dev-container-repo/ng-gateway-api"

            case "${GH_EVENT_NAME}" in
                release)
                    DATA_AGGREGATOR_TAGS="${DOCKER_REPO_DATA_AGGREGATOR}:${{ github.event.release.tag_name }}"
                    GATEWAY_API_TAGS="${DOCKER_REPO_GATEWAY_API}:${{ github.event.release.tag_name }}"
                ;;
                pull_request | push)
                    docker_tag_with_branch
                    DATA_AGGREGATOR_TAGS="${DOCKER_REPO_DATA_AGGREGATOR}:${DOCKER_TAG}"
                    GATEWAY_API_TAGS="${DOCKER_REPO_GATEWAY_API}:${DOCKER_TAG}"
                ;;
                *)
                    echo "${GH_EVENT_NAME} not implemented yet"
                    exit 1
                ;;
            esac

            echo "DATA_AGGREGATOR_TAGS: $DATA_AGGREGATOR_TAGS"
            echo "GATEWAY_API_TAGS: $GATEWAY_API_TAGS"
            echo "DATA_AGGREGATOR_TAGS=$DATA_AGGREGATOR_TAGS" >> $GITHUB_ENV
            echo "GATEWAY_API_TAGS=$GATEWAY_API_TAGS" >> $GITHUB_ENV
             
      - name: Docker build and push DataAggregator
        uses: docker/build-push-action@v2
        with:
          file: ./src/DataAggregator/Dockerfile
          TAGS: |
            ${{ env.DATA_AGGREGATOR_TAGS }}
          push: true
          context: ./
             
      - name: Docker build and push Gateway API
        uses: docker/build-push-action@v2
        with:
          file: ./src/GatewayAPI/Dockerfile
          TAGS: |
            ${{ env.GATEWAY_API_TAGS }}
          push: true
          context: ./


