name: sync-postman-collection

on: [push]

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{github.token}}
  sync_postman_collections:
    name: Sync Postman collection w/ latest develop
    environment: Postman
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Postman credentials
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .env
          contents: POSTMAN_API_KEY=${{secrets.POSTMAN_API_TOKEN}}
          write-mode: append
      - name: Create Portman configuration for Gateway API
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: cliopts.json
          contents: '{"postmanWorkspaceName":"Team Workspace","collectionName":"Gateway API (develop)"}'
          write-mode: append
      - name: Download the latest spec
        run: |
          wget https://raw.githubusercontent.com/radixdlt/radixdlt-network-gateway/develop/gateway-api-spec.yaml
      - name: Replace hardcoded values with variables
        run: |
          sed -i 's/{{baseUrl}}/{{gatewayBaseUrl}}/g' gateway-api-spec.yaml &&\          
          sed -i 's/mainnet/"{{network}}"/g' gateway-api-spec.yaml &&\
          sed -i 's/rdx1qspacch6qjqy7awspx304sev3n4em302en25jd87yrh4hp47grr692cm0kv88/"{{sender_address_1}}"/g' gateway-api-spec.yaml &&\
          sed -i 's/rdx1qspcvwwuf8s549zyspz683v4n93g9kzpn6u6a9yalwzt00zghg75lmsftwv29/"{{receiver_address_1}}"/g' gateway-api-spec.yaml &&\
          sed -i 's/rv1qf2x63qx4jdaxj83kkw2yytehvvmu6r2xll5gcp6c9rancmrfsgfwttnczx/"{{validator_address_1}}"/g' gateway-api-spec.yaml &&\
          sed -i 's/xrd_rr1qy5wfsfh/"{{native_token_rri}}"/g' gateway-api-spec.yaml
      - run: cat gateway-api-spec.yaml
      - name: Generate and upload Postman's Gateway API collection
        run: |
          npx @apideck/portman -l gateway-api-spec.yaml --syncPostman true --envFile .env --cliOptionsFile cliopts.json
      - name: Validate against RCNET
        run: |
          npx @apideck/portman -l gateway-api-spec.yaml --runNewman
