name: sync-postman-collection

on:
  push:
    branches:
      - develop

jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{github.token}}
  sync_postman_collections:
    name: Sync Postman collection w/ latest develop
    environment: Postman
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Postman credentials
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .env
          contents: POSTMAN_API_KEY=${{secrets.POSTMAN_API_TOKEN}}
          write-mode: append
      - name: Create Portman configuration for Gateway API
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: cliopts.json
          contents: '{"postmanWorkspaceName":"Team Workspace","collectionName":"Gateway API (develop)"}'
          write-mode: append
      - name: Download the latest spec
        run: |
          wget https://raw.githubusercontent.com/radixdlt/radixdlt-network-gateway/develop/gateway-api-spec.yaml
        run: ls
      - name: Generate and upload Postman's Gateway API collection
        run: |
          npx @apideck/portman -l gateway-api-spec.yaml --syncPostman true --envFile .env --cliOptionsFile cliopts.json \
            --postmanUid 14449947-5d6c29d7-673a-482b-8fac-c2fa8f3adb4a
